[connections.snowflake]
account = "HZLIQZF-IF30047"
user = "SIBICJ02"
password = "eTSvviZzKHM6SJY"
warehouse = "COMPUTE_WH"
database = "SNOWFLAKE_LEARNING_DB"
schema = "PUBLIC"
role = "ACCOUNTADMIN"

[gemini]
api_key = "AIzaSyBuNwU-eLLiV4yjItYTPHclCihoSAf3ppc"
