[connections.snowflake]
account = "your_snowflake_account"
user = "your_username"
password = "your_password"
warehouse = "your_warehouse"
database = "SNOWFLAKE_LEARNING_DB"
schema = "PUBLIC"
role = "your_role_if_any"

[gemini]
api_key = "enter your gemini api"
